# Generated by Django 5.2.4 on 2025-07-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок', max_length=150, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='Введите текст', verbose_name='Содержимое')),
                ('preview', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='blog_records/photo', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Укажите дату создания', verbose_name='Дата создания')),
                ('published', models.BooleanField(default=True, help_text='Укажите статус', verbose_name='Опубликовано')),
                ('views_counter', models.PositiveIntegerField(default=0, help_text='Укажите количество просмотров', verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Запись блога',
                'verbose_name_plural': 'Записи блога',
                'ordering': ['title'],
            },
        ),
    ]
