# Generated by Django 5.2.4 on 2025-07-18 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование категории', max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, help_text='Введите описание категории', null=True, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование продукта', max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, help_text='Введите описание продукта', null=True, verbose_name='Описание продукта')),
                ('photo', models.ImageField(blank=True, help_text='Загрузите фото продукта', null=True, upload_to='products/photo', verbose_name='Фото')),
                ('price', models.IntegerField(help_text='Введите цену продукта', verbose_name='Цена')),
                ('created_at', models.DateField(help_text='Укажите дату создания', verbose_name='Дата создания')),
                ('updated_at', models.DateField(default=models.DateField(help_text='Укажите дату создания', verbose_name='Дата создания'), help_text='Укажите дату изменения', verbose_name='Дата изменения')),
                ('category', models.ForeignKey(blank=True, help_text='Введите категорию продукта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['category', 'name'],
            },
        ),
    ]
