# Generated by Django 5.2.4 on 2025-07-18 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=datetime.date(2025, 7, 18), help_text='Укажите дату создания', verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateField(default=datetime.date(2025, 7, 18), help_text='Укажите дату изменения', verbose_name='Дата изменения'),
        ),
    ]
