# Generated by Django 5.2.4 on 2025-07-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_created_at_alter_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='отсутствует', help_text='Введите описание продукта', null=True, verbose_name='Описание продукта'),
        ),
    ]
