# Generated by Django 5.2.4 on 2025-08-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=False, help_text='Введите статус публикации', verbose_name='Опубликовано'),
        ),
    ]
