# Generated by Django 5.2.4 on 2025-08-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'permissions': [('can_unpublish_product', 'can unpublish product')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
